### ISSUE TITLE
Enhancement: Download streams as is (without joining the segments) [stream mirroring]

### ISSUE THREAD

**Issue by spookyahell** [coldsofttech/pym3u8downloader#10]
Not currently supported: Download m3u8 streams as is, leaving segment files in their respective (sub-)folders (where possible)

**Comment by spookyahell** [comment]
Oops, sorry: I tapped my fingers to fast, fixing it now...

**Comment by spookyahell** [comment]
Sample stream:
https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8

**Comment by coldsofttech** [comment]
Thanks for the suggestion @spookyahell. This enhancement is in place now. Please refer to below link for usage.

https://github.com/coldsofttech/pym3u8downloader/blob/main/README.md#m3u8downloader
